apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hello-login-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: hello-login-secrets
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: hello-login/staging
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: hello-login/staging
        property: JWT_SECRET
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: hello-login/staging
        property: MAIL_PASSWORD
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: hello-login/staging
        property: MAIL_USERNAME
    - secretKey: MAIL_DEFAULT_SENDER
      remoteRef:
        key: hello-login/staging
        property: MAIL_DEFAULT_SENDER
